### ISSUE TITLE
Output role_id instead of role_name from asg module

### ISSUE THREAD

**Issue by colincoleman** [telia-oss/terraform-aws-ecs#7]
The values of aws_iam_role.<role>.name and aws_iam_role.<role>.id are the same.
Other resources that will consume this value are typically documented as looking for id - for example
https://www.terraform.io/docs/providers/aws/r/iam_role_policy.html.

To avoid confusion I suggest exporting role_id instead of role_name from the ASG module.
I see that this would have knock on changes to "cluster" and perhaps more...

**Comment by itsdalmo** [comment]
Currently, it seems like spotfleet cluster is the only module which outputs `role_id`:
https://github.com/search?q=org%3Atelia-oss+role_id&type=Code

Suggest you change this to `role_name` unless we decide to change [all modules](https://github.com/search?q=org%3Atelia-oss+role_name&type=Code) to use `role_id` instead.

**Comment by colincoleman** [comment]
I am biting the bullet and making all the changes necessary to bring these modules in line with the examples in the terraform documentation.

**Comment by itsdalmo** [comment]
Our modules will need a major refactor to work with terraform `0.12`, and I think we'll just start outputting everything at that point.
